name: meu primeiro ci

on: [push, pull_request]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - name: config python
          uses: actions/python-setup@v3
          with: 
            python-version: '3.10'
        - name: intalar dependencias
          run: pip install -r requirements.txt
        - name: intalar dependencias
          run: pytest test_app.py

            
                

              
               


        
