name: meu primeiro ci

on: [push, pull_request]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - name: config python
          uses: actions/python_setup@v3
          with: pythonv -version
                

              
               


        
